##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##


world_collision_checker_cfg:
  cache: null #{"cube": 41, "capsule": 0, "sphere": 0}
  checker_type: "MESH" # ["PRIMITIVE", "BLOX", "MESH"]
  max_distance: 0.1
 

constraint:
  primitive_collision_cfg:
    weight: 1.0
    use_sweep: False
    classify: False
    sum_distance: False
    compute_esdf: True
    activation_distance: 0.0
  self_collision_cfg:
    weight: 1.0
    classify: False
    activation_distance: 0.0
  bound_cfg:
    weight: [5000.0, 5000.0, 5000.0,5000.0]
    activation_distance: [0.0,0.0,0.0,0.0] # for position, velocity, acceleration and jerk


convergence:
  grasp_cfg:
    weight: [1.0, 1.0, 0.0] # angle, dist, regu
    perturb_strength_bound: [0.01, 0.02]
  cspace_cfg:
    weight: 1.0
    terminal: True
    run_weight: 1.0
  null_space_cfg:
    weight: 1.0
    terminal: True
    run_weight: 1.0
    
 